-- Backstreet Cafe — one-off import of the current menu and gallery.
-- Run AFTER schema.sql, in the Supabase SQL editor.
-- Safe to re-run: it clears both tables first.

begin;

delete from public.menu_items;

insert into public.menu_items
  (name, description, price, category, image_url, tags, badge, sort_order)
values
  ('Eggs your way (gfo)', 'Toasted sourdough, two poached eggs, relish (home-made), baby spinach.', 14.90, 'BREAKFAST', 'https://backstreet-cafe-menu.netlify.app/images/Breakfast/Eggs your way (gfo).jpg', '{"gfo"}', null, 10),
  ('Green Brekky Burrito', 'Scrambled eggs, crispy bacon, baby spinach & Mexican melted cheese, all wrapped in a spinach tortilla, with our house-made chipotle & romesco sauce.', 23.90, 'BREAKFAST', 'https://backstreet-cafe-menu.netlify.app/images/Breakfast/Green Brekky Burrito.jpg', '{}', 'Backstreet Favourite', 20),
  ('Brekky Burger', 'Scrambled eggs, crispy bacon, baby spinach & Mexican melted cheese blend, all wrapped in a spinach tortilla, with our house-made chipotle & romesco sauce.', 17.90, 'BREAKFAST', 'https://backstreet-cafe-menu.netlify.app/images/Breakfast/Brekky Burger.jpg', '{}', null, 30),
  ('Smashed Avo (gfo)(v)', 'Toasted sourdough,, all home-made radish, chilli, whipped feta, one poached egg, dukkah', 22.90, 'BREAKFAST', 'https://backstreet-cafe-menu.netlify.app/images/Breakfast/Smashed-Avo.jpg', '{"gfo","v"}', null, 40),
  ('Eggs Benedict (gfo)', 'Smashed avocado, poached eggs, baby spinach, house hollandaise, english muffin', 24.90, 'BREAKFAST', 'https://backstreet-cafe-menu.netlify.app/images/Breakfast/Eggs Benedict (gfo).jpg', '{"gfo"}', null, 50),
  ('Breadless Benedict (gf)', 'Corn fritters, smashed avocado, poached eggs, baby spinach, house hollandaise', 25.90, 'BREAKFAST', 'https://backstreet-cafe-menu.netlify.app/images/Breakfast/Breadless Benedict (gf).jpg', '{"gf"}', 'Signature', 60),
  ('Corn Fritters (gf)(v)', 'Smashed avocado, whipped feta, one poached egg', 24.90, 'BREAKFAST', 'https://backstreet-cafe-menu.netlify.app/images/Breakfast/Corn Fritters (gf)(v).jpg', '{"gf","v"}', null, 70),
  ('Mushroom Bruschetta (gfo)', 'All home- made, Garlic and thyme mushrooms, one poached egg, baby spinach, whipped feta, basil pesto, dukkah, toasted sourdough', 23.90, 'BREAKFAST', 'https://backstreet-cafe-menu.netlify.app/images/Breakfast/Mushroom Bruschetta (gfo).jpg', '{"gfo"}', null, 80),
  ('Big Breakfast (gfo)', 'Two Poached eggs, bacon, roasted tomato, cheese Kransky sausage, relish (home-made), house baked beans, mushrooms, hash browns, toasted sourdough.', 29.90, 'BIG_BREAKFAST', 'https://backstreet-cafe-menu.netlify.app/images/Big Breakfast/Big Breakfast (gfo).jpg', '{"gfo"}', null, 10),
  ('Big Vege (gfo)(v)', 'Two Poached eggs, roasted tomato, relish (home-made), house baked beans, mushrooms, hash browns, smashed avocado, whipped feta, toasted sourdough.', 29.90, 'BIG_BREAKFAST', 'https://backstreet-cafe-menu.netlify.app/images/Big Breakfast/Big Vege (gfo)(v).jpg', '{"gfo","v"}', null, 20),
  ('House Made Baked Beans (gfo)', 'Two fried eggs, cheese Kransky sausage, toasted sourdough, spinach and relish.', 26.90, 'BIG_BREAKFAST', 'https://backstreet-cafe-menu.netlify.app/images/Big Breakfast/House Made Baked Beans (gfo).jpg', '{"gfo"}', null, 30),
  ('Berry Pancake', 'Berry compote, maple syrup, ice cream', 22.90, 'SWEET_BREAKFAST', 'https://backstreet-cafe-menu.netlify.app/images/Sweet Breakfast/Berry Pancake.jpg', '{"v"}', null, 10),
  ('Grilled banana (v) Pancake', 'Grilled banana, crispy bacon, maple syrup, ice cream', 23.90, 'SWEET_BREAKFAST', 'https://backstreet-cafe-menu.netlify.app/images/Sweet Breakfast/Grilled banana (v) Pancake.jpg', '{"v"}', null, 20),
  ('Sunshine fruit bowl (v)(gfo)', 'Seasonal fresh fruits, homemade granola, COYO coconut yoghurt, honey, pepitas & shredded coconut', 19.90, 'SWEET_BREAKFAST', 'https://backstreet-cafe-menu.netlify.app/images/Sweet Breakfast/Sunshine Fruit bowl (v) (gfo).jpg', '{"v","gfo"}', null, 30),
  ('Banana bread french toast', 'Cinnamon vanilla banana bread, topped with creamy ice-cream, maple syrup and a berry compote', 22.90, 'SWEET_BREAKFAST', 'https://backstreet-cafe-menu.netlify.app/images/Sweet Breakfast/Banana Bread French Toast.jpg', '{}', null, 40),
  ('Banana Bread (v)(gfo)', 'Artisan banana bread by noosa gourmet, topped with creamy ice cream, maple syrup and berry compote.', 6.90, 'SWEET_BREAKFAST', 'https://backstreet-cafe-menu.netlify.app/images/Sweet Breakfast/Banana Bread (v)(gfo).jpg', '{"v","gfo"}', null, 50),
  ('Biscoff Pancake', 'Fluffy pancake topped with Biscoff crumble, rich Biscoff sauce, warm Biscoff drizzle and vanilla ice cream.', 24.90, 'SWEET_BREAKFAST', 'https://backstreet-cafe-menu.netlify.app/images/Sweet Breakfast/Biscoff Pancake.jpg', '{"v"}', null, 60),
  ('Bacon + Egg', 'poached egg and bacon w/ toasted sourdough (gfo)', 12.00, 'KIDS_STUFF', 'https://backstreet-cafe-menu.netlify.app/images/Kids Stuff/Bacon + Egg.jpg', '{"gfo"}', null, 10),
  ('Avocado toast', 'Toast with smashed avocado and cherry tomato (gfo)', 12.00, 'KIDS_STUFF', 'https://backstreet-cafe-menu.netlify.app/images/Kids Stuff/Avocado toast.jpg', '{"gfo"}', null, 20),
  ('Pancakes (v)', 'w/ maple syrup + ice cream', 15.00, 'KIDS_STUFF', 'https://backstreet-cafe-menu.netlify.app/images/Kids Stuff/Pancakes (v).jpg', '{"v"}', null, 30),
  ('Kids fruit & Yoghurt Bowl', 'Coconut yoghurt with seasonal fruit, house granola & a drizzle of honey', 12.00, 'KIDS_STUFF', 'https://backstreet-cafe-menu.netlify.app/images/Kids Stuff/Kids fruit & Yoghurt Bowl.jpg', '{}', null, 40),
  ('Toast', 'with jam, vegemite, or peanut butter (gfo)', 9.00, 'KIDS_STUFF', 'https://backstreet-cafe-menu.netlify.app/images/Kids Stuff/Toast .jpg', '{"gfo"}', null, 50),
  ('Signature Smash', '140g smashed beef patty, fresh lettuce, ripe tomato, onion, pickles and our house-made secret sauce', 19.90, 'BURGERS', 'https://backstreet-cafe-menu.netlify.app/images/BackStreet Burgers/Signature Smash.jpg', '{}', null, 10),
  ('Hot Chick', 'Crispy deep-fried chicken breast, chipotle house-made sauce, iceberg lettuce, pickles and melted cheese', 19.90, 'BURGERS', 'https://backstreet-cafe-menu.netlify.app/images/BackStreet Burgers/Hot Chick.jpg', '{}', null, 20),
  ('Double Trouble', 'Double smashed beef patties, double cheese, crispy bacon and our signature house sauce', 21.90, 'BURGERS', 'https://backstreet-cafe-menu.netlify.app/images/BackStreet Burgers/Double Trouble.jpg', '{}', null, 30),
  ('The Challenging Burger', 'Stacked high with double smashed beef patties, double bacon, melted cheese, lettuce, tomato, onion and pickles, finished with our house sauce, crispy onion rings and a mozzarella stick', 27.90, 'BURGERS', 'https://backstreet-cafe-menu.netlify.app/images/BackStreet Burgers/The Challenging Burger.jpg', '{}', null, 40),
  ('Fish Taco', 'Crispy battered flathead, red cabbage slaw, house-made roasted garlic lemon aioli and Brazilian-style vinaigrette, served in a toasted flour tortilla. 1 for $7 or 3 for $19', 7.00, 'LUNCH', 'https://backstreet-cafe-menu.netlify.app/images/Lunch Menu/Fish Taco.jpg', '{}', null, 10),
  ('Big Mac Taco', 'All the Big Mac vibes, seasoned ground beef, iceberg lettuce, mexican cheese blend, onion, pickles and our signature Big Mac-style sauce. 1 for $7 or 3 for $19', 7.00, 'LUNCH', 'https://backstreet-cafe-menu.netlify.app/images/Lunch Menu/Big Mac Taco.jpg', '{}', null, 20),
  ('Chicken Taco', 'Grilled chicken, iceberg lettuce, Mexican cheese blend, crispy bacon and house-made chipotle sauce, served in a toasted flour tortilla. 1 for $7 or 3 for $19', 7.00, 'LUNCH', 'https://backstreet-cafe-menu.netlify.app/images/Lunch Menu/Chicken Taco.jpg', '{}', null, 30),
  ('Fish & Chips', 'Crispy battered flathead served with crunchy chips and house-made roasted garlic lemon aioli', 19.90, 'LUNCH', 'https://backstreet-cafe-menu.netlify.app/images/Lunch Menu/Fish & Chips.jpg', '{}', null, 40),
  ('Toastie', 'Grilled chicken, house-made pesto, roasted capsicum and signature melted cheese', 20.00, 'LUNCH', 'https://backstreet-cafe-menu.netlify.app/images/Lunch Menu/Toastie.jpg', '{}', null, 50),
  ('Cobb Salad', 'Red cabbage slaw, Brazilian-style vinaigrette salsa, boiled egg, Mexican cheese, corn, fresh avocado, cucumber and crispy bacon', 19.00, 'LUNCH', 'https://backstreet-cafe-menu.netlify.app/images/Lunch Menu/Cobb Salad.jpg', '{}', null, 60),
  ('Bowl of chips with aioli', 'Crispy chips served with aioli', 9.00, 'SIDES', 'https://backstreet-cafe-menu.netlify.app/images/Sides/Bowl of chips with aioli.jpg', '{}', null, 10),
  ('Sweet potato chips', 'Crispy sweet potato chips', 11.00, 'SIDES', 'https://backstreet-cafe-menu.netlify.app/images/Sides/Sweet potato chips.jpg', '{}', null, 20),
  ('Mozzarella sticks', 'Golden fried mozzarella sticks', 12.00, 'SIDES', 'https://backstreet-cafe-menu.netlify.app/images/Sides/Mozzarella sticks.jpg', '{}', null, 30),
  ('Onion rings', 'Crispy golden onion rings', 10.00, 'SIDES', 'https://backstreet-cafe-menu.netlify.app/images/Sides/Onion rings.jpg', '{}', null, 40),
  ('Halloumi', 'Premium grilled halloumi cheese', 7.00, 'EXTRA_BITS', 'https://backstreet-cafe-menu.netlify.app/images/Extra Bits/Halloumi.jpg', '{}', null, 10),
  ('Smoked Salmon', 'Premium smoked salmon', 7.00, 'EXTRA_BITS', 'https://backstreet-cafe-menu.netlify.app/images/Extra Bits/Smoked Salmon.jpg', '{}', null, 20),
  ('Cheese Kransky', 'Grilled cheese kransky sausage', 7.00, 'EXTRA_BITS', 'https://backstreet-cafe-menu.netlify.app/images/Extra Bits/Cheese Kransky.jpg', '{}', null, 30),
  ('Corn Fritter', 'House-made corn fritter', 7.00, 'EXTRA_BITS', 'https://backstreet-cafe-menu.netlify.app/images/Extra Bits/Corn Fritter.jpg', '{}', null, 40),
  ('Bacon', 'Crispy bacon strips', 6.00, 'EXTRA_BITS', 'https://backstreet-cafe-menu.netlify.app/images/Extra Bits/Bacon.jpg', '{}', null, 50),
  ('Hash Browns', 'Crispy golden hash browns', 6.00, 'EXTRA_BITS', 'https://backstreet-cafe-menu.netlify.app/images/Extra Bits/Hash Browns.jpg', '{}', null, 60),
  ('Mushrooms', 'Sautéed mushrooms', 6.00, 'EXTRA_BITS', 'https://backstreet-cafe-menu.netlify.app/images/Extra Bits/Mushrooms.jpg', '{}', null, 70),
  ('Smashed Avocado', 'Fresh smashed avocado', 6.00, 'EXTRA_BITS', 'https://backstreet-cafe-menu.netlify.app/images/Extra Bits/Avo.jpg', '{}', null, 80),
  ('House Beans', 'House-made baked beans', 6.00, 'EXTRA_BITS', 'https://backstreet-cafe-menu.netlify.app/images/Extra Bits/House Beans.jpg', '{}', null, 90),
  ('Gluten Free Toast', 'Gluten free bread toasted', 2.00, 'EXTRA_BITS', 'https://images.unsplash.com/photo-1509440159596-0249088772ff?q=80&w=800&auto=format&fit=crop', '{"gf"}', null, 100),
  ('Extra Poached Egg', 'Perfectly poached egg', 3.00, 'EXTRA_BITS', 'https://backstreet-cafe-menu.netlify.app/images/Extra Bits/Extra Poached Egg.jpg', '{}', null, 110),
  ('Scrambled Egg', 'Fluffy scrambled eggs', 1.00, 'EXTRA_BITS', 'https://backstreet-cafe-menu.netlify.app/images/Extra Bits/Scrambled.jpg', '{}', null, 120),
  ('Chips w/ aioli', 'Crispy chips served with aioli', 9.00, 'EXTRA_BITS', 'https://backstreet-cafe-menu.netlify.app/images/Extra Bits/Chips w: Aioli.jpg', '{}', null, 130),
  ('Sweet Potato Fries w/ aioli', 'Crispy sweet potato fries served with aioli', 11.00, 'EXTRA_BITS', 'https://backstreet-cafe-menu.netlify.app/images/Extra Bits/Sweet Potatoes Fries w: Aioli.jpg', '{}', null, 140),
  ('Espresso', 'GUN COTTON COFFEE - locally roasted', 4.50, 'DRINKS_HOT', 'https://backstreet-cafe-menu.netlify.app/images/Drinks/Espresso.jpg', '{}', null, 10),
  ('Macchiato / Piccolo', 'GUN COTTON COFFEE - locally roasted', 4.80, 'DRINKS_HOT', 'https://backstreet-cafe-menu.netlify.app/images/Drinks/Macchiato or Piccolo.jpg', '{}', null, 20),
  ('Long Black / Flat White / Cappuccino / Mocha / Latte', 'GUN COTTON COFFEE - locally roasted', 5.00, 'DRINKS_HOT', 'https://backstreet-cafe-menu.netlify.app/images/Drinks/Cappuccino.jpg', '{}', null, 30),
  ('Spiced Chai', 'Traditional spiced chai latte (dirty +$0.5)', 5.00, 'DRINKS_HOT', 'https://backstreet-cafe-menu.netlify.app/images/Drinks/Spiced Chai.jpg', '{}', null, 40),
  ('Hot Chocolate', 'Rich and creamy hot chocolate', 4.80, 'DRINKS_HOT', 'https://backstreet-cafe-menu.netlify.app/images/Drinks/Hot Chocolate.jpg', '{}', null, 50),
  ('Matcha S/L', 'Small $6 or Large $6.9', 6.00, 'DRINKS_HOT', 'https://backstreet-cafe-menu.netlify.app/images/Drinks/Matcha.jpg', '{}', null, 60),
  ('Loose Leaf Tea - English Breakfast', 'English breakfast tea served with milk', 4.50, 'DRINKS_HOT', 'https://backstreet-cafe-menu.netlify.app/images/Drinks/Loose Leaf Tea - English breakfast tea served with milk .jpg', '{}', null, 70),
  ('Loose Leaf Tea - Green Tea Mint + Rose', 'Refreshing green tea with mint and rose', 4.50, 'DRINKS_HOT', 'https://backstreet-cafe-menu.netlify.app/images/Drinks/Loose Leaf Tea - Green Tea Mint + Rose.jpg', '{}', null, 80),
  ('Loose Leaf Tea - Peppermint', 'Soothing peppermint tea', 4.50, 'DRINKS_HOT', 'https://backstreet-cafe-menu.netlify.app/images/Drinks/Loose Leaf Tea - Peppermint .jpg', '{}', null, 90),
  ('Affogato', 'Espresso poured over vanilla ice cream', 6.50, 'DRINKS_SWIRLS', 'https://backstreet-cafe-menu.netlify.app/images/Drinks/Affogato.jpg', '{}', null, 10),
  ('Iced Coffee', 'Served over ice, ice-cream and topped with whipped cream', 8.90, 'DRINKS_SWIRLS', 'https://backstreet-cafe-menu.netlify.app/images/Drinks/Iced Coffee.jpg', '{}', null, 20),
  ('Iced Chocolate', 'Served over ice, ice-cream and topped with whipped cream', 8.90, 'DRINKS_SWIRLS', 'https://backstreet-cafe-menu.netlify.app/images/Drinks/Iced Chocolate.jpg', '{}', null, 30),
  ('Iced Mocha', 'Served over ice, ice-cream and topped with whipped cream', 8.90, 'DRINKS_SWIRLS', 'https://backstreet-cafe-menu.netlify.app/images/Drinks/Iced Mocha.jpg', '{}', null, 40),
  ('Coffee Frappe', 'Blended espresso, ice, vanilla syrup, ice-cream & milk', 10.00, 'DRINKS_SWIRLS', 'https://backstreet-cafe-menu.netlify.app/images/Drinks/Coffee Frappe.jpg', '{}', null, 50),
  ('Smoothie - Mango', 'Coconut milk, honey and Greek natural yoghurt', 11.90, 'DRINKS_COLD', 'https://backstreet-cafe-menu.netlify.app/images/Drinks/Smoothies - Mango.jpg', '{}', null, 10),
  ('Smoothie - Banana', 'Coconut milk, honey and Greek natural yoghurt', 11.90, 'DRINKS_COLD', 'https://backstreet-cafe-menu.netlify.app/images/Drinks/Smoothies - banana.jpg', '{}', null, 20),
  ('Smoothie - Mixed Berry', 'Coconut milk, honey and Greek natural yoghurt', 11.90, 'DRINKS_COLD', 'https://backstreet-cafe-menu.netlify.app/images/Drinks/Smoothies - mix berry.jpg', '{}', null, 30),
  ('Açaí Smoothie', 'Brazilian açaí, banana, honey and apple juice', 13.90, 'DRINKS_COLD', 'https://backstreet-cafe-menu.netlify.app/images/Drinks/Açaí Smoothie.jpg', '{}', null, 40),
  ('Milkshake - Caramel', 'Classic caramel milkshake', 8.90, 'DRINKS_COLD', 'https://backstreet-cafe-menu.netlify.app/images/Drinks/Milkshakes - Caramelo.jpg', '{}', null, 50),
  ('Milkshake - Vanilla', 'Classic vanilla milkshake', 8.90, 'DRINKS_COLD', 'https://backstreet-cafe-menu.netlify.app/images/Drinks/Milkshakes - vanilla.jpg', '{}', null, 60),
  ('Milkshake - Chocolate', 'Classic chocolate milkshake', 8.90, 'DRINKS_COLD', 'https://backstreet-cafe-menu.netlify.app/images/Drinks/Milkshake - Chocolate.jpg', '{}', null, 70),
  ('Milkshake - Strawberry', 'Classic strawberry milkshake', 8.90, 'DRINKS_COLD', 'https://backstreet-cafe-menu.netlify.app/images/Drinks/Milkshake - Strawberry.jpg', '{}', null, 80),
  ('Ultimate Oreo Shake', 'Premium Oreo milkshake', 13.80, 'DRINKS_COLD', 'https://backstreet-cafe-menu.netlify.app/images/Drinks/Ultimate Oreo Shake.jpg', '{}', null, 90),
  ('Ultimate Pink Cloud', 'Premium pink cloud milkshake', 13.80, 'DRINKS_COLD', 'https://backstreet-cafe-menu.netlify.app/images/Drinks/Ultimate Pink Cloud.jpg', '{}', null, 100),
  ('Iced Long Black', 'Double shot espresso on ice, with water', 5.00, 'DRINKS_COLD', 'https://backstreet-cafe-menu.netlify.app/images/Drinks/Iced Long Black.jpg', '{}', null, 110),
  ('Iced Latte', 'Double shot espresso on ice, with milk', 6.00, 'DRINKS_COLD', 'https://backstreet-cafe-menu.netlify.app/images/Drinks/Iced latte : Iced chai.jpg', '{}', null, 120),
  ('Iced Chai', 'Double shot chai on ice, with milk', 6.00, 'DRINKS_COLD', 'https://backstreet-cafe-menu.netlify.app/images/Drinks/Iced latte : Iced chai.jpg', '{}', null, 130),
  ('Allies Cold Pressed Juice - Orange', 'Fresh cold pressed orange juice', 8.00, 'DRINKS_COLD', 'https://backstreet-cafe-menu.netlify.app/images/Drinks/Allies cold pressed juices - Orange.jpg', '{}', null, 140),
  ('Allies Cold Pressed Juice - Ginger Apple', 'Fresh cold pressed ginger apple juice', 8.00, 'DRINKS_COLD', 'https://backstreet-cafe-menu.netlify.app/images/Drinks/Allies cold pressed juices - Ginger apple.jpg', '{}', null, 150),
  ('Allies Cold Pressed Juice - Green Juice', 'Fresh cold pressed green juice', 8.00, 'DRINKS_COLD', 'https://backstreet-cafe-menu.netlify.app/images/Drinks/Allies cold pressed juices - green juice.jpg', '{}', null, 160),
  ('Allies Cold Pressed Juice - Love Beets', 'Fresh cold pressed beetroot juice', 8.00, 'DRINKS_COLD', 'https://backstreet-cafe-menu.netlify.app/images/Drinks/Allies cold pressed juices - lovebeets.jpg', '{}', null, 170),
  ('Allies Cold Pressed Juice - Sublime Pine', 'Fresh cold pressed pineapple juice', 8.00, 'DRINKS_COLD', 'https://backstreet-cafe-menu.netlify.app/images/Drinks/Allies cold pressed juices - sublime pine.jpg', '{}', null, 180),
  ('House Iced Tea', 'Green Tea Mint & Rose Peppermint blend, house-made passionfruit syrup, fresh mixed berries', 9.00, 'DRINKS_COLD', 'https://backstreet-cafe-menu.netlify.app/images/Drinks/House Iced Tea.jpg', '{}', null, 190),
  ('Iced Matcha', 'Choose your preferred milk and check with our staff for today''s syrup options.', 7.20, 'DRINKS_COLD', 'https://backstreet-cafe-menu.netlify.app/images/Drinks/Iced Matcha.jpg', '{}', null, 200),
  -- The Beer & Cocktails category is seeded hidden, so these load but do not
  -- show on the public website until staff switch the section back on.
  ('Corona', 'Classic Mexican beer', 9.00, 'BEER_COCKTAILS', 'https://backstreet-cafe-menu.netlify.app/images/Beer & Cocktails/corona.jpg', '{}', null, 10),
  ('Great Northern Super Crisp', 'Australian lager', 8.00, 'BEER_COCKTAILS', 'https://backstreet-cafe-menu.netlify.app/images/Beer & Cocktails/Great Northern Super Crisp.jpg', '{}', null, 20),
  ('Matsos Ginger Beer', 'Refreshing ginger beer', 10.00, 'BEER_COCKTAILS', 'https://backstreet-cafe-menu.netlify.app/images/Beer & Cocktails/Matsos Ginger Beer.jpg', '{}', null, 30),
  ('Mimosa', 'Classic champagne and orange juice cocktail', 9.00, 'BEER_COCKTAILS', 'https://backstreet-cafe-menu.netlify.app/images/Beer & Cocktails/Mimosa.jpg', '{}', null, 40),
  ('Espresso Martini', 'A classic caffeine kick with premium vodka and fresh espresso', 15.00, 'BEER_COCKTAILS', 'https://backstreet-cafe-menu.netlify.app/images/Beer & Cocktails/Espresso Martini.jpg', '{}', null, 50),
  ('Aperol Spritz', 'Italian aperitif cocktail', 12.00, 'BEER_COCKTAILS', 'https://backstreet-cafe-menu.netlify.app/images/Beer & Cocktails/Aperol Spritz.jpg', '{}', null, 60),
  ('Frozen Piña Colada', 'Tropical blend of pineapple, coconut and rum', 18.00, 'BEER_COCKTAILS', 'https://backstreet-cafe-menu.netlify.app/images/Beer & Cocktails/Frozen Pina Colada.jpg', '{}', null, 70),
  ('House Spirits', 'Selection of house spirits', 10.00, 'BEER_COCKTAILS', 'https://backstreet-cafe-menu.netlify.app/images/Beer & Cocktails/House Spirits.jpg', '{}', null, 80);

delete from public.gallery_images;

insert into public.gallery_images (image_url, alt_text, sort_order)
values
  ('/assets/media/gallery-1.png', 'Backstreet Cafe gallery image 1', 10),
  ('/assets/media/gallery-2.png', 'Backstreet Cafe gallery image 2', 20),
  ('/assets/media/gallery-3.png', 'Backstreet Cafe gallery image 3', 30),
  ('/assets/media/gallery-4.png', 'Backstreet Cafe gallery image 4', 40),
  ('/assets/media/gallery-5.png', 'Backstreet Cafe gallery image 5', 50),
  ('/assets/media/gallery-6.png', 'Backstreet Cafe gallery image 6', 60),
  ('/assets/media/cafe.png', 'Backstreet Cafe gallery image 7', 70);

commit;
